services:
  db:
    image: pgvector/pgvector:pg17
    container_name: laboratorio4_pgvector

    environment:
      POSTGRES_DB: laboratorio4_agents
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: